### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/idv-test#1]
I am getting the following messages in `compare.html` and no images are being generated:

```java
Exception in thread "main" java.lang.UnsupportedClassVersionError: ucar/unidata/idv/DefaultIdv :
Unsupported major.minor version 52.0 at

java.lang.ClassLoader.defineClass1(Native Method) at
java.lang.ClassLoader.defineClass(Unknown Source) at
java.security.SecureClassLoader.defineClass(Unknown Source) at
java.net.URLClassLoader.defineClass(Unknown Source) at
java.net.URLClassLoader.access$100(Unknown Source) at 
java.net.URLClassLoader$1.run(Unknown Source) at
java.net.URLClassLoader$1.run(Unknown Source) at
java.security.AccessController.doPrivileged(Native Method) at
java.net.URLClassLoader.findClass(Unknown Source) at 
java.lang.ClassLoader.loadClass(UnknownSource) at
sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) at
java.lang.ClassLoader.loadClass(Unknown Source) at
sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

```bash
$ docker --version
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by julienchastang** [comment]
Oh my gosh. I had forgotten all about this. Yes, this project is probably quite out-of-date. The error you are seeing is a Java mismatch between the Java byte code and the JVM, if I recall. What is your ultimate aim here? It probably would not be too much work to revive this. I believe @piqueen314 has also expressed interest in ameliorating IDV testing.

**Comment by lesserwhirls** [comment]
My goal was a quick test of the IDV against the current TDS running on thredds.ucar.edu, and I recalled your work to get these tests Dockerized. A problem was reported regarding the TDS post update to 4.6.11, but it was isolated to a single dataset, and regenerating the index files for that dataset fixed the issue. My idea was that running this could have helped find out if there were other datasets with a similar problem.

**Comment by julienchastang** [comment]
I will try to revive this, this week.

**Comment by julienchastang** [comment]
Sean, just to give you an update here, this project depended on the defunct `idv-gui` Docker image now `cloudidv`. I've been wrapping my head around the new way of doing things and I think I mostly understand, but will require a little time still before this is revived.

**Comment by lesserwhirls** [comment]
Thanks Julien - no rush!

**Comment by julienchastang** [comment]
For example: http://149.165.169.172/compare.html

**Comment by julienchastang** [comment]
@lesserwhirls You should be back in business. See the `readme.md` I just checked in. Let me know if I can help with anything else.

**Comment by lesserwhirls** [comment]
Thanks @julienchastang !
