### ISSUE TITLE
THREDDS Server Parameterization

### ISSUE THREAD

**Issue by julienchastang** [Unidata/idv-test#9]
Work with @lesserwhirls on desired THREDDS server parameterization.

**Comment by lesserwhirls** [comment]
The biggest parameterization would be the ability to change the top level domain of the data being used in the test bundles. For example, changing all data requests from `thredds.ucar.edu` to `thredds-test.unidata.ucar.edu`. We have IDV plugins that do just that, so perhaps the parameterization could be used to tell the IDV if it needs to use one of those plugins?
